/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ngyb_jni_FirstJniFile */

#ifndef _Included_com_ngyb_jni_FirstJniFile
#define _Included_com_ngyb_jni_FirstJniFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ngyb_jni_FirstJniFile
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ngyb_jnihelloworld_FirstJniFile_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
